#!/bin/bash
############################
# MAKE TERMINAL GREAT AGAIN!
############################

#-----------------
# LS color options
#-----------------

# Here is a good link to changing colors: https://geoff.greer.fm/lscolors/

OS=$(uname) # Run `uname` command to get current OS

# Run necessary colors setting for IOS or Linux
if [[ "$OS" == "Linux" ]]; then
	export LSCOLORS=di=1;36:ln=1;35:so=1;32:pi=1;33:ex=1;31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=34;43 # Linux
elif [[ "$OS" == "Darwin" ]]; then
    export CLICOLOR=2    
	export LSCOLORS=GxFxCxDxBxegedabagaced # IOS
fi


#------------------------------
# BASH command history settings
#------------------------------
# Great resource: https://www.shellhacks.com/tune-command-line-history-bash/

# ignorespace: don’t save lines which begin with a <space> character; erasedups: eliminate duplicates across the whole history
export HISTCONTROL=ignorespace:erasedups
# Increase size
export HISTSIZE=100000000000
export HISTFILESIZE=10000000000
# Append Bash Commands to History File
shopt -s histappend
# History time format
HISTTIMEFORMAT="%d/%m/%y %T "

#after each command save and reload history

log_bash_persistent_history()
{
        [[
        $(history 1) =~ ^\ *[0-9]+\ +([^\ ]+\ [^\ ]+)\ +(.*)$
        ]]
        local date_part="${BASH_REMATCH[1]}"
        local command_part="${BASH_REMATCH[2]}"
        if [ "$command_part" != "$PERSISTENT_HISTORY_LAST" ]
        then
                echo $date_part "|" "$command_part" >> ~/.persistent_history
                export PERSISTENT_HISTORY_LAST="$command_part"
        fi
}

# Stuff to do on PROMPT_COMMAND
run_on_prompt_command()
{
        log_bash_persistent_history
}

export PROMPT_COMMAND="history -a; history -c; history -r; run_on_prompt_command; $PROMPT_COMMAND"

#----------------------------------------
# Load the shell dotfiles, and then some:
#----------------------------------------
# Credit: https://github.com/mathiasbynens/dotfiles/blob/master/.bash_profile#L4-L10
# * ~/.path can be used to extend `$PATH`.
# All BASH functions are here
# All BASH aliases are here
# * ~/.extra can be used for other settings you don’t want to commit.

#for file in ~/.{bash-functions,bash-aliases,bash-prompt,exports,aliases,functions,extra}; do
#		[ -r "$file" ] && [ -f "$file" ] && source "$file";
#	done;
#	unset file;

for file in ~/.{bash-functions,bash-aliases,bash-prompt,exports,extra}; do
	if	[ -e "${file}" ] ; then
		source "${file}"
	else
		touch "${file}" # need to fix this section
		dot=$(basename "${file}")
		echo "source ~/dotfiles/terminal/"${dot}"" > "${file}"
		source "${file}"
	fi;
done;
unset file;

	#------------------------------------------
# Add tab completion for many Bash commands
#------------------------------------------
# Credit: https://github.com/mathiasbynens/dotfiles/blob/master/.bash_profile#L28-L33

if which brew &> /dev/null && [ -f "$(brew --prefix)/share/bash-completion/bash_completion" ]; then
	source "$(brew --prefix)/share/bash-completion/bash_completion";
elif [ -f /etc/bash_completion ]; then
	source /etc/bash_completion;
fi;

#-------------------------------------------------------------------------------
# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
#-------------------------------------------------------------------------------
# Credit: https://github.com/mathiasbynens/dotfiles/blob/master/.bash_profile#L40-L41
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;


#----------
# Miniconda
#----------
export PATH="$HOME/miniconda3/bin:$PATH"

#---------
# Language
#---------
export LANG=en_US.utf8

#----------------------
# Pointing RStudio to R
#----------------------
export RSTUDIO_WHICH_R=/usr/local/Cellar/r/3.5.3/bin/R

#-------------------------
# Changing HOMEBREW editor
#-------------------------

export HOMEBREW_EDITOR="/usr/local/bin/vim"
